#!/bin/bash

# Let r be the distance on the paper between (CLON, CLAT) and (CLON, LAT+45)
# (drawn as a dashed, red line)
# let g = r / sin(CLAT)
# r is the length of a vertical gnomon standing at (CLON, CLAT)
# g is the length of a polar gnomon, fixed at (0, 90) or (0, -90)
# see README.md for more info
# released under GNU GPLv3, see COPYING file

LON=9.133 # longitude of the observer
LAT=39.248 # latitude of the observer
RANGE=70
LEMN_MERID=15 # meridian with analemma
FILE=/tmp/gnomonic-sundial.ps # name of the output file
WALL_INCL=60 # wall inclination: e.g., 0=horizontal, 45=oblique facing up, 90=vertical
WALL_DECL=-30 # wall declination: e.g., 0=south, 90=east, -90=west, -45=south-west, etc.

TILT=23.437 # earth's tilt angle, constant
CLON=`echo "rot_lon($WALL_DECL, $WALL_INCL, $LON, $LAT)" | bc -l data/functions.bc`
CLAT=`echo "rot_lat($WALL_DECL, $WALL_INCL, $LAT)" | bc -l data/functions.bc`
POL_ANG=`echo "pol_ang($WALL_DECL, $WALL_INCL, $LAT)" | bc -l data/functions.bc`
ANALEMMA=`mktemp` || exit 1 # tmp file with analemma coordinates
ITALIC=`mktemp` || exit 1 # tmp file with italic and babylonian lines

# clear variables
gmt clear conf &> /dev/null
gmt clear history &> /dev/null

# set media size
gmt set PS_MEDIA A3

# gnomonic projection
SIZE=27 # size in cm
gmt psbasemap -P -Rg -JF$CLON/$CLAT/$RANGE/${SIZE}c -p$POL_ANG+w$CLON/$CLAT -Bg15/ -X1.5c -K > $FILE
gmt pscoast -R -J -B -Di -Glightgray -N1/0.25p,- -W1/ -O -K >> $FILE 

# equator and tropics (=> equinoxes and solstices)
echo -e "0 0\n120 0\n240 0" | gmt psxy -R -J -Ap -L -O -K >> $FILE # equator
echo -e "0 $TILT\n120 $TILT\n240 $TILT" | gmt psxy -R -J -Ap -L -O -K >> $FILE # tropic of cancer 
echo -e "0 -$TILT\n120 -$TILT\n240 -$TILT" | gmt psxy -R -J -Ap -L -O -K >> $FILE # tropic of capricorn

# analemma on the chosen meridian
paste <(awk -v m=$LEMN_MERID '{print $1 + m}' data/sun-time-shift.txt) data/sun-declination.txt > $ANALEMMA
gmt psxy $ANALEMMA -R -L -J -O -K -W1,red >> $FILE

# italic hours
DA=`echo "sunset($LAT, $TILT)" | bc -l data/functions.bc`
DB=`echo "sunset($LAT, -$TILT)" | bc -l data/functions.bc`
for d in `seq 0 15 90`; do
    echo $d | awk -v LON=$LON -v DA=$DA -v DB=$DB -v TILT=$TILT '{print $1 + LON - DA " " TILT}{print $1 + LON - DB " " TILT*(-1)}' > $ITALIC
    head -2 $ITALIC | gmt psxy -R -J -W1,green,- -O -K >> $FILE
done

# babylonian hours
DA=`echo "sunset($LAT, $TILT)" | bc -l data/functions.bc`
DB=`echo "sunset($LAT, -$TILT)" | bc -l data/functions.bc`
for d in `seq 0 -15 -90`; do
    echo $d | awk -v LON=$LON -v DA=$DA -v DB=$DB -v TILT=$TILT '{print $1 + LON + DA " " TILT}{print $1 + LON + DB " " TILT*(-1)}' > $ITALIC
    head -2 $ITALIC | gmt psxy -R -J -W1,blue,- -O -K >> $FILE
done

# star some random dates
NUMDAY=`date '+%j' -d "2018-04-25"` # Italian liberation day
sed -n "${NUMDAY}p" $ANALEMMA | gmt psxy -R -J -Sa.2 -Gred -O -K >> $FILE
NUMDAY=`date '+%j' -d "2018-10-31"` # Halloween
sed -n "${NUMDAY}p" $ANALEMMA | gmt psxy -R -J -Sa.2 -Gred -O -K >> $FILE

# mark center, location and radius length
RADIUS=`echo "radius_lat($CLAT)" | bc -l data/functions.bc`
echo -e "$CLON $CLAT" | gmt psxy -R -J -Sx.2 -Wred  -O -K >> $FILE
echo -e "$LON $LAT" | gmt psxy -R -J -Sx.2 -Wred -O -K >> $FILE
echo -e "$CLON $RADIUS" | gmt psxy -R -J -S+.2 -Wred  -O -K >> $FILE
echo -e "$CLON $CLAT\n$CLON $RADIUS" | gmt psxy -R -J -W0.5,red,- -O -K >> $FILE

# clean conf and tmp
gmt clear conf; gmt clear history
rm $ANALEMMA
rm $ITALIC
ls -l $FILE
